### ISSUE TITLE
UDOO NEO SERIAL LIBRARIES EXAMPLES

### ISSUE THREAD

**Issue by waltervl** [UDOOboard/Neo-Docs#18]
Please change the following:
1. Remove "And How To Port Them" from the title. there is nothing about porting.
2. Add the following at the beginning of the page:
Serial Libraries Communication Samples for UDOO Board

Copyright (C) 2014 Ekironji Solutions

These example’s scripts are meant to demonstrate how to implement a uni\bidirectional communication between an Arduino sketch (running on SAM3X Arduino Compatible processor) and a binary application on iMX6 Linux processor.

The Arduino sketch will remain the same no matter which programming language you’ll use to develop the binary on iMX6.

There are two example scripts for each programming language: C, Java, PHP, Python.You can find the whole repo in our Github Channel. [add link, see 3.]

Each program is meant to be executed while the matching Arduino Sketch is running on SAM3X:

arduino_serial_example.ino
c_serial_example.c
java_serial_example.java
php_serial_example.php
python_serial_example.py

arduino_serial_example_bidirectional.ino
c_serial_example_bidirectional.c
java_serial_example_bidirectional.java
php_serial_example_bidirectional.php
python_serial_example_bidirectional.py
3. Add source page link to this page else we cannot find the sources: https://github.com/UDOOboard/serial_libraries_examples
4. Please update layout as it has a complete other css as the other pages
5. Replace "sudo pip install pyserial" with "sudo apt-get install python-serial" see http://www.udoo.org/forum/threads/pyserial-error-with-udoo-neo.3294/
6. Add the github source page to the Udoo Dual/Quad pages too: http://www.udoo.org/docs/Serial_Libraries/index.html

**Comment by waltervl** [comment]
Please update this in the documentation as it is very confusing now. I see issue 1 is solved but the rest is not.

Also indicate that they have to replace /dev/ttsSo by /dev/ttyMCC as the library is written for the Quad.

**Comment by waltervl** [comment]
Almost there, thank you! Please just update the layout of php and java sub page.

**Comment by UDOOboard** [comment]
Thanks to you for having pointed out, and all the help.

All should be fixed now. I'm closing the issue.
