### ISSUE TITLE
Cookbook Arduino M4 examples have PWM issue

### ISSUE THREAD

**Issue by waltervl** [UDOOboard/Neo-Docs#21]
The examples with Analogwrite in them do not follow the rules according the PWM issue and will fail:
http://www.udoo.org/docs-neo/Debugging_&_Troubleshooting/Arduino_PWM_Issue.html
Affected examples
http://www.udoo.org/docs-neo/Cookbook_Arduino_M4/RGB_led.html
http://www.udoo.org/docs-neo/Cookbook_Arduino_M4/Two_color_common_cathode_led.html

Also affected is http://www.udoo.org/docs-neo/Arduino_M4_Processor/Sketch_examples.html RGB example but i think this whole section can be deleted as it is has the same purpose as the Cookbook.

**Comment by ektor5** [comment]
Hi,
All fixed in 75189494ca65035dd21d0ced0efc1c612d3d311d and in 005b60f18386f071a0827228c2acd3e0a42272e1. [Sketch_example](http://www.udoo.org/docs-neo/Arduino_M4_Processor/Sketch_examples.html) was already deleted.

Thanks,
Ek5
