### ISSUE TITLE
Neo Arduino doc does not mention I2C-2 SDA/SCL is not enabled.

### ISSUE THREAD

**Issue by waltervl** [UDOOboard/Neo-Docs#22]
No were in the Arduino part of the Neo docs is mentioned that the I2C-2 bus that is reserved for the SDA/SCL pins is default assigned to the Linux core and has to be disabled for Linux with the DTE.
http://www.udoo.org/docs-neo/Cookbook_Linux/Device_Tree_Editor.html

**Comment by ektor5** [comment]
Well, actually the "**I2C-2: SNAP-IN Bricks connector**" paragraph states:

> **By default the snap-in connector is assigned to the A9** and it’s possible to control it by Linux driver. The I2C signal are also available on SDA - SCL pins and on pins 36/37.
> If you need to use this on the M4 Arduino core, **you need to remove it from the A9 core**, right-clicking on the corresponding pins and removing it.
> After a reboot it will be possible to connect an external I2C device to the SDA SCL pins and control it from the Arduino M4 core.

So I think this issue is invalid,
Ek5

**Comment by waltervl** [comment]
The I2C-2 is as you write mentioned on the linux side of the documentation but you really have to search when you want to use I2C on the Arduino side and find that it is not working. The first thing you look is in the Arduino part of the Neo documentation but there you cannot find it. So please make a reference to the dte in the Arduino part of the documentation. For example in the difference page stating that I2C is not working by default.
